name: json_stream_parser_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_markdown_plus: ^1.0.5
  google_fonts: ^6.3.2
  json_stream_parser:
    git:
      url: https://github.com/ComsIndeed/json_stream_parser_dart.git
      ref: c38827c639f12f1d7d2fa054335273071fe52a6b
  provider: ^6.1.5+1
  google_generative_ai: 0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
